<?php

/**
 * Test class for GateKeeper.
 * Generated by PHPUnit on 2011-10-04 at 23:07:18.
 */
class GateKeeperTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var GateKeeper
	 * 
	 */
	private $keep;
	private $data = array();
	private $post;
	private $tables;

	/**
	 * @var integer
	 */
	public function a__construct() {
		$this->login();

		$this->tables = array(
				"news", "event",
		);
		$this->loadAltsaaaa();
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function loadAltsaaaa() {
		

		foreach ($this->tables as $type) {

			$className = ucfirst($type);

			$this->data[$type] = array();


			$this->insert($type, "allow", array(
			));

			$this->insert($type, "deny", array(
					rand(0, 10000),
					rand(0, 10000),
					rand(0, 10000),
					rand(0, 10000),
					3238746,
			));

			$this->insert($type, "52", array(
					52
			));

			$this->insert($type, "52,56", array(
					52, 56
			));

			$this->insert($type, "52,1000", array(
					52, 1000
			));
		}
	}

	public function insert($type, $name, array $access) {
		$className = ucwords($type);
		$this->post = new $className;

		$this->post->insert();
		$this->data[$type][$name] = $this->post->id;
		//echo "data $type $name = {$this->post->id}" . PHP_EOL;


		foreach ($access as $a) {
			$acs_bit = new AccessRelations;
			$acs_bit->type = $type;
			$acs_bit->id = $this->post->id;
			$acs_bit->access = $a;
			$acs_bit->insert();
		}
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */

	public function testA() {
		var_dump(debug_backtrace());
		$this->login();		
	}

	public function login() {
		$user = 381;
		$pass = null;
		$identity = new InnsidaIdentity($user, $pass);

		$identity->authenticate();
		Yii::app()->user->login($identity);
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function logout() {
		Yii::app()->user->logout();
	}
	
	public function atestAccess() {
		$this->login();
		//print_r(Yii::app()->user->access);
	}

	public function atestLoggedIn() {
		$this->login();
		$keep = new GateKeeper();

		foreach ($this->tables as $type) {
			$this->assertTrue($keep->check($type, $this->data[$type]["allow"]));
			$this->assertFalse($keep->check($type, $this->data[$type]["deny"]));

			
			$this->assertTrue($keep->check($type, $this->data[$type]["52"]));
			$this->assertTrue($keep->check($type, $this->data[$type]["52,56"]));
			$this->assertFalse($keep->check($type, $this->data[$type]["52,1000"]));
		}
	}

	public function atestLoggedOut() {
		$this->logout();
		$keep = new GateKeeper();
		

		foreach ($this->tables as $type) {

			$this->assertTrue($keep->check($type, $this->data[$type]["allow"]));
			$this->assertFalse($keep->check($type, $this->data[$type]["deny"]));

			$this->assertFalse($keep->check($type, $this->data[$type]["52"]));
			$this->assertFalse($keep->check($type, $this->data[$type]["52,56"]));
			$this->assertFalse($keep->check($type, $this->data[$type]["52,1000"]));
		}
	}

}
