<?php

/**
 * Test class for GateKeeper.
 * Generated by PHPUnit on 2011-10-04 at 23:07:18.
 */
class GateKeeperTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var GateKeeper
	 * 
	 */
	private $data = array();
	private $post;
	private $tables;

	/**
	 * @var integer
	 */
	public function __construct() {
		$this->initTables();
		$this->printTestAssumptions();
		$this->setUpOnce();
		$this->initGateKeeper();
	}

	private function initTables() {
		$this->tables = array(
				"news", "event",
		);
	}

	private function printTestAssumptions() {
		if (Yii::app()->user->isGuest) {
			echo "Tester for gjester" . PHP_EOL;
		} else {
			echo "Tester for bruker: " . Yii::app()->user->name . PHP_EOL;
			echo "VIKTIG: antar at brukeren kun har accesstilgang id 52 og 56" . PHP_EOL . PHP_EOL;
		}
	}
	
	private function initGateKeeper() {
		$this->gatekeeper = new GateKeeper;
	}

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUpOnce() {


		foreach ($this->tables as $type) {
			$className = ucfirst($type);
			$this->data[$type] = array();
			$this->insert($type, "allow", array());
			$this->insert($type, "deny", array(
					rand(0, 10000),
					rand(0, 10000),
					rand(0, 10000),
					rand(0, 10000),
					3238746,
			));

			$this->insert($type, "52", array(
					52
			));

			$this->insert($type, "52,56", array(
					52, 56
			));

			$this->insert($type, "52,1000", array(
					52, 1000
			));
		}
	}

	public function insert($type, $name, array $access) {
		$className = ucwords($type);
		$this->post = new $className;

		$this->post->insert();
		$this->data[$type][$name] = $this->post->id;
		//echo "data $type $name = {$this->post->id}" . PHP_EOL;


		foreach ($access as $a) {
			$acs_bit = new AccessRelations;
			$acs_bit->type = $type;
			$acs_bit->id = $this->post->id;
			$acs_bit->access = $a;
			$acs_bit->insert();
		}
	}

	public function login() {
		$user = 381;
		$pass = null;
		$identity = new InnsidaIdentity($user, $pass);

		$identity->authenticate();
		Yii::app()->user->login($identity);
	}

	public function testLoggedIn() {
		if (Yii::app()->user->isGuest)
			return;

		foreach ($this->tables as $type) {
			$this->assertTrue($this->gatekeeper->hasAccess($type, $this->data[$type]["allow"]));
			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["deny"]));


			$this->assertTrue($this->gatekeeper->hasAccess($type, $this->data[$type]["52"]));
			$this->assertTrue($this->gatekeeper->hasAccess($type, $this->data[$type]["52,56"]));
			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["52,1000"]));
		}
	}

	public function testLoggedOut() {
		if (!Yii::app()->user->isGuest) {
			return;
		}


		foreach ($this->tables as $type) {

			$this->assertTrue($this->gatekeeper->hasAccess($type, $this->data[$type]["allow"]));
			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["deny"]));

			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["52"]));
			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["52,56"]));
			$this->assertFalse($this->gatekeeper->hasAccess($type, $this->data[$type]["52,1000"]));
		}
	}

}
