<?php

require_once dirname(__FILE__) . '/../../../components/InnsidaIdentity.php';

/**
 * Test class for InnsidaIdentity.
 * Generated by PHPUnit on 2011-11-08 at 17:22:51.
 */
class InnsidaIdentityTest extends PHPUnit_Framework_TestCase {

	public function test_getName() {
		$data = "id,blabla,skole,blabla,username,sigurhol,yndlingsfarge,grønn";
		$name = InnsidaIdentity::getUsernameFromData($data);
		
		$this->assertEquals("sigurhol", $name);
	}

}

?>
