<?php

/**
 * Test class for Access.
 * Generated by PHPUnit on 2011-10-10 at 14:13:19.
 */
class AccessTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Access
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Access;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testInsertMembership().
	 */
	public function testInsertMembership() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteMembership().
	 */
	public function testDeleteMembership() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteAccessRelation().
	 */
	public function testDeleteAccessRelation() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertAccessRelation().
	 */
	public function testInsertAccessRelation() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAccessRelation().
	 */
	public function testGetAccessRelation() {
		// Remove the following lines when you implement this test.
		Access::deleteAllAccessRelation("event", 2);
		Access::insertAccessRelation(2, 4, "event");
		Access::insertAccessRelation(2, 5, "event");
		Access::insertAccessRelation(2, 6, "event");
		Access::insertAccessRelation(2, 7, "event");
		
		$expected = array(4,5,6,7);
		$this->assertEquals($expected, Access::getAccessRelation(2, "event"));
	}

	/**
	 * @todo Implement testDeleteAccessDefinition().
	 */
	public function testDeleteAccessDefinition() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertAccessDefinition().
	 */
	public function testInsertAccessDefinition() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInnerSQLAllowedTypeIds().
	 */
	public function testInnerSQLAllowedTypeIds() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

}

?>
