<?php

require_once dirname(__FILE__) . '/../../../models/Article.php';

/**
 * Test class for Article.
 * Generated by PHPUnit on 2011-11-05 at 21:54:14.
 */
class ArticleTest extends PHPUnit_Framework_TestCase {
	
	private function getArticle() {
		$article = new Article();
		return $article;
	}

	public function test_construct() {
		$article = $this->getArticle();
		$article->save();
		$this->assertNotNull($article->primaryKey);
	}
	
	public function test_setAccess() {
		$access = array(1,2,3,4);
		$article = $this->getArticle();
		$article->access = $access;
		$article->save();
		
		$article2 = Article::model()->findByPk($article->primaryKey);
		$this->assertEquals($access, $article2->access);
	}
	
}
