<?php

require_once dirname(__FILE__) . '/../../../../models/Event.php';

/**
 * Test class for Event.
 * Generated by PHPUnit on 2011-10-02 at 01:00:21.
 */
class EventTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Event
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Event;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testHasSignup().
	 */
	public function testHasSignup() {
		// Remove the following lines when you implement this test.

	}

	/**
	 * @todo Implement testGetSignup().
	 */
	public function testGetSignup() {
		// Remove the following lines when you implement this test.

	}

	/**
	 * @todo Implement testGetNews().
	 */
	public function testGetNews() {
		// Remove the following lines when you implement this test.

	}

}

?>
