<?php /*
Hva som maa testes

SetUp
=====

Lager bruker aa teste mot
Lage gruppe og teste mot

Tester
======

Lagring opp mot database
========================

* Sjekke at den kaster exceptions
* Den lagrer riktig naar:
	bare news
	bare event
	bare event og news
	alle tre

* ikke lagrer
	event naar hasEvent = 0
	news naar hasNews = 0
	signup naar hasSignup = 0
	signup naar hasEvent = 0

Tilganger
=================
* Laster dem opp

* Forskjellige tilganger til forskjellige brukere
	Admin
		All tilgang
	Gruppesjef
		All tilgang paa gruppen
		Legge ut paa hovedsiden
		Redigere sine egne
	Bruker:
		Legge ut paa gruppesider
		Redigere sine egne paa gruppesider

*/

require_once dirname(__FILE__) . '/../../../models/NewsEventForm.php';

/**
 * Test class for NewsEventForm.
 * Generated by PHPUnit on 2011-10-14 at 17:42:09.
 */
class NewsEventFormTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var NewsEventForm
	 */
	protected $model;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$News = News::model();
		$Event = Event::model();
		$this->model = new NewsEventForm;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testRules().
	 */
	public function testRules() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSave().
	 */
	public function testSave() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testTestInput().
	 */
	public function testTestInput() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
						'This test has not been implemented yet.'
		);
	}

}

?>

